# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests on ${{ matrix.py }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "pypy-3.9"
          - "pypy-3.8"
          - "pypy-3.7"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip flit
        flit install --deps=develop
    - name: Lint with flake8
      run: flake8 clickhouse_cli --count --max-complexity=31 --show-source --statistics
    - name: Test with pytest
      run: pytest --cov=clickhouse_cli
